pull_request_rules:
  - name: label dependabot PRs
    conditions:
      - author=dependabot[bot]
      - -title=Bump .* from .* to .*$
    actions:
      label:
        add: [chore]
  - name: merge dependabot's PRs
    conditions:
      - author=dependabot[bot]
      - -title=Bump .* from .* to .*$
      - status-success=test
      - status-success=build
      - status-success=lint
    actions:
      merge:
        method: squash
