version: '3.8'
services:
  build:
    build: .
    volumes:
      - .:/two-app:z
    working_dir: /two-app
    # Sources bashrc to run startup scripts to wait for dependencies
    command: bundle exec fastlane test-release