import {AccessibilityProps} from 'react-native';

export const a11y = ({
  accessibilityActions,
  accessibilityElementsHidden,
  accessibilityHint,
  accessibilityIgnoresInvertColors,
  accessibilityLabel,
  accessibilityLiveRegion,
  accessibilityRole,
  accessibilityState,
  accessibilityValue,
  accessibilityViewIsModal,
  accessible,
  onAccessibilityAction,
  onAccessibilityEscape,
  onAccessibilityTap,
  importantForAccessibility,
}: AccessibilityProps): AccessibilityProps => ({
  accessibilityActions,
  accessibilityElementsHidden,
  accessibilityHint,
  accessibilityIgnoresInvertColors,
  accessibilityLabel,
  accessibilityLiveRegion,
  accessibilityRole,
  accessibilityState,
  accessibilityValue,
  accessibilityViewIsModal,
  accessible,
  onAccessibilityAction,
  onAccessibilityEscape,
  onAccessibilityTap,
  importantForAccessibility,
});
