default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  before_all do
    setup_circle_ci
  end

  lane :alpha do |options|
    register_devices(devices_file: "./devices.txt")

    match(type: "adhoc", readonly: is_ci)

    increment_build_number(xcodeproj: "two.xcodeproj")
    gym(export_method: "ad-hoc")

    firebase_app_distribution(
      app: ENV['APP_ID'],
      groups: ENV["GROUPS"] || options[:groups],
      release_notes: options[:notes] || "",
    )
    
    commit_version_bump(
      message: "iOS 🍏 build number bump [skip ci]",
      force: true,
      xcodeproj: "two.xcodeproj"
    )
  end
end
