default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  before_all do
    setup_circle_ci
  end

  lane :alpha do |options|
    File.write('AppStoreConnectApiKey.p8', ENV["APPLE_APP_STORE_CONNECT_API_KEY"])

    api_key = app_store_connect_api_key(
      key_id: ENV["APPLE_APP_STORE_CONNECT_API_KEY_ID"],
      issuer_id: ENV["APPLE_APP_STORE_CONNECT_API_KEY_ISSUER_ID"],
      key_filepath: "./fastlane/AppStoreConnectApiKey.p8",
      in_house: false
    )

    register_devices(devices_file: "./devices.txt")

    match(type: "adhoc", readonly: is_ci, api_key: api_key)

    increment_build_number(xcodeproj: "two.xcodeproj")
    gym(export_method: "ad-hoc")

    firebase_app_distribution(
      app: ENV['APP_ID'],
      groups: "ios-family",
      release_notes: options[:notes] || "",
    )
    
    commit_version_bump(
      message: "iOS 🍏 build number bump [skip ci]",
      force: true,
      xcodeproj: "two.xcodeproj"
    )
  end
end
