# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"

  lane :test do
    gradle(task: "test")
  end

  lane :alpha do
    increment_version_code(
        gradle_file_path: "../app/build.gradle",
    )
    
    commit_android_version_bump(
      message: "Android 🤖 version code bump -> #{version_code} [skip ci]",
      gradle_file_folder: '../app'
    )

    store_password = ENV["ANDROID_KEY_PASSWORD"]
    key_password = ENV["ANDROID_KEY_PASSWORD"]
    
    releaseFilePath = File.join(Dir.pwd, "..", "my-release-key.keystore")
    gradle(task: 'clean')
    gradle(
      task: 'assemble',
      build_type: 'Release',
      print_command: false,
      properties: {
        "android.injected.signing.store.file" => releaseFilePath,
        "android.injected.signing.store.password" => store_password,
        "android.injected.signing.key.alias" => "my-key-alias",
        "android.injected.signing.key.password" => key_password,
      }
    )

    firebase_app_distribution(
        app: "1:585621126829:android:278c6064cd8e899e27d024",
        groups: "android-family",
        release_notes: ""
    )
  end

  desc "Submit a new Beta Build to Play Store"
  lane :beta do
    store_password = ENV["ANDROID_KEY_PASSWORD"]
    key_password = ENV["ANDROID_KEY_PASSWORD"]
    
    releaseFilePath = File.join(Dir.pwd, "..", "my-release-key.keystore")
    gradle(task: 'clean')
    gradle(
      task: 'assemble',
      build_type: 'Release',
      print_command: false,
      properties: {
        "android.injected.signing.store.file" => releaseFilePath,
        "android.injected.signing.store.password" => store_password,
        "android.injected.signing.key.alias" => "my-key-alias",
        "android.injected.signing.key.password" => key_password,
      }
    )
    upload_to_play_store(
      track: 'internal'
    )
  end

end
