name: Update Cocoapods Dependencies
on:
  workflow_run:
    workflows: ["Dependabot PR Check"]
    types: 
      - completed

permissions:
  contents: write
  pull-requests: write

jobs:
  run:
    name: Run pod install
    runs-on: macos-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: c-hive/gha-yarn-cache@v1

      - run: yarn install --non-interactive --frozen-lockfile --network-timeout 100000

      - name: Cache pods
        uses: actions/cache@v1
        with:
          path: ios/Pods
          key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-

      - name: Install Cocoapods Packages
        run: pushd ios && pod install --verbose && popd

      - uses: stefanzweifel/git-auto-commit-action@v4.11.0
        with:
          commit_message: Bump Cocoapods Packages
          branch: ${{ github.head_ref }}
