name: Test

on:
  push:
    branches:
      - '**'
      - '!master'

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12'
      - run: yarn install --network-timeout 100000
      - run: yarn test
  build:
    name: build
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - run: yarn install
      - run: gem install bundler
      - uses: actions/cache@v2
        with:
          path: Pods
          key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-
      - name: iOS Build
        # xcbuild takes 20+ minutes, more than 2x
        # android, so we just install pods as a minor
        # sanity check
        run: |
          cd ios
          pod deintegrate
          pod install
          cd ../
      - name: Android Build
        run: |
          cd android
          bundle install
          bundle exec fastlane test_release
          cd ../
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '12'
      - run: yarn install
      - run: yarn eslint
      - run: yarn tsc
