name: Test

on:
  push:
    branches:
      - '**'
      - '!master'

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12'
      - run: yarn install
      - run: yarn test
  build:
    name: build
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - run: yarn install
      - run: cd ios; pod deintegrate && pod install; cd ../
      - name: Install Fastlane
        run: sudo gem install fastlane -NV
      - name: Install Bundler
        run: gem install bundler
      - name: Fastlane Alpha
        run: |
          cd android
          bundle install
          bundle exec fastlane test-release --env beta
          cd ../
      # - uses: actions/setup-java@v1
      #   with:
      #     java-version: 11
      # - uses: eskatos/gradle-command-action@v1
      #   with:
      #     build-root-directory: android
      #     gradle-version: 6.2
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '12'
      - run: yarn install
      - run: yarn eslint
      - run: yarn tsc