name: Firebase App Distribution

on:
  push:
    branches:
      - master

jobs:
  ios:
    name: Publish iOS
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.1.0
        with:
          ref: 'master'
      - name: Configure Git
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "Release Bot"
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '12'
      - run: yarn install
      - name: Install Firebase CLI
        run: npm install -g firebase-tools
      - uses: actions/cache@v2
        with:
          path: Pods
          key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-
      - name: Install Pods
        run: cd ios; pod install; cd ../
      - name: Fastlane Alpha
        run: |
          cd ios
          bundle install
          bundle exec fastlane alpha --env beta
          cd ../
        env:
          ENVFILE: .env.prod
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          FASTLANE_PASSWORD: ${{ secrets.FASTLANE_PASSWORD }}
          MATCH_GIT_BASIC_AUTHORIZATION: ${{ secrets.MATCH_GIT_BASIC_AUTHORIZATION }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
      - name: Merge Version Changes
        run: |
          git reset --hard
          git clean -f -d
          git pull --rebase
      - name: Push Changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

  android:
    name: Publish Android
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.1.0
        with:
          ref: 'master'
      - name: Configure Git
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "Release Bot"
      - name: Set up Ruby v2.6
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6
      - name: Setup Node v12
        uses: actions/setup-node@v1
        with:
          node-version: '12'
      - run: yarn install
      - name: Install Firebase CLI
        run: npm install -g firebase-tools
      - name: Write Secret Key
        run: cd android; echo '${{ secrets.ANDROID_PUBLISH_KEY }}' > key.json; cd ../
      - name: Write Publish Keystore
        run: cd android; echo ${{ secrets.ANDROID_RELEASE_KEYSTORE }} | base64 --decode > my-release-key.keystore; cd ../
      - name: Install Fastlane
        run: sudo gem install fastlane -NV
      - name: Install Bundler
        run: gem install bundler
      - name: Fastlane Alpha
        run: |
          cd android
          bundle install
          bundle exec fastlane alpha --env beta
          cd ../
        env:
          ENVFILE: .env.prod
          ANDROID_KEY_PASSWORD: ${{ secrets.ANDROID_KEY_PASSWORD }}
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      - name: Merge Version Changes
        run: |
          git reset --hard
          git clean -f -d
          git pull --rebase
      - name: Push Changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
