name: Test

on:
  push:
    branches:
      - '*'
      - '!master'

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: install
      - name: Test
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: test